message_playerJoin: 玩家进入,人数(%d,%d)
message_kickplayer: 服务器已满或正在进行游戏
message_gameReady: 游戏还有 %d 秒开始
message_onGamePlay: 游戏开始!
message_onPlayerRunAway: 由于玩家逃跑，重新开始准备流程
message_onPlayerRoomWin: 玩家 %s 战胜了 %s 夺得了一场比赛的胜利!本轮比赛剩余 %d 场
message_AllRoomsEnd: 本轮比赛所有玩家已经全部战斗完毕!
message_NextRound: 下一轮比赛参与的玩家有 %s
message_RoundPreStart: 第 %d 轮比赛准备开始
message_FinalWinner: 最终赢家 %s
#游戏开始之前的延迟
game_Countdown: 10
#游戏大厅的XYZ坐标
game_LobbyPos_x: 1.0
game_LobbyPos_y: 64.0
game_LobbyPos_z: 3.0
#比赛地图的坐标列表
game_ArenaPosList:
  - x: 0.0
    y: 64.0
    z: 128.0
  - x: 0.0
    y: 64.0
    z: 256.0
  - x: 128.0
    y: 64.0
    z: 256.0
  - x: 256.0
    y: 64.0
    z: 256.0